testId: azure-function-load-test
displayName: Load test for Azure Function
description: Simple GET load test
testPlan: ./test-plan.jmx
engineInstances: 1
configuration:
  splitAllCSVs: false
  env:
    - name: TARGET_URL
      value: https://lohnazurefunction.azurewebsites.net/api/DllFunctionCalculate