name: Azure Load Test

on:
  push:
    branches:
      - poc/benchmark-concept-azure-function
  workflow_dispatch:  # or use `push`, `schedule`, etc.

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure Load Test
        uses: azure/load-testing@v1.1.27
        with:
          loadTestConfigFile: .azureloadtest/loadtest-config.yaml
          resourceGroup: POC
          loadTestResource: POCAzureFunctionLoadTesting
